const  API_BASE_URL_DEVELOPMENT = 'http://localhost:5031/api';
const  API_BASE_URL_PRODUCTION = 'http://appname.dockersomething.net';

const ENDPOINTS = {
    GET_ALL_COUNTRIES: 'countries',
    GET_COUNTRIE_BY_ID: 'countries',
    CREATE_COUNTRY: 'countries',
    UPDATE_COUNTRY: 'countries',
    DELETE_POST_BY_ID: 'countries'
};

const development = {
    API_URL_GET_ALL_COUNTRIES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_COUNTRIES}`,
    API_URL_GET_COUNTRY_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_COUNTRIE_BY_ID}`,
    API_URL_CREATE_COUNTRY: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_COUNTRY}`,
    API_URL_UPDATE_COUNTRY: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_COUNTRY}`,
    API_URL_DELETE_POST_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_POST_BY_ID}`
};

const production = {
    API_URL_GET_ALL_COUNTRIES: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_COUNTRIES}`,
    API_URL_GET_COUNTRY_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_COUNTRIE_BY_ID}`,
    API_URL_CREATE_COUNTRY: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_COUNTRY}`,
    API_URL_UPDATE_COUNTRY: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_COUNTRY}`,
    API_URL_DELETE_POST_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_POST_BY_ID}`
};

const Constants = process.env.NODE_ENV === 'development' ? development : production;

export default Constants;
