// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiflheimsForge.Data;

#nullable disable

namespace NiflheimsForge.Data.Data.Migrations
{
    [DbContext(typeof(NiflheimsForgeDBContext))]
    [Migration("20240311095947_NullableIdMigration")]
    partial class NullableIdMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NiflheimsForge.Core.Models.Country", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e735a52-dc10-4ccb-b390-7cd791111a82"),
                            Description = "This is country number 1",
                            Name = "Country 1"
                        },
                        new
                        {
                            Id = new Guid("efbf6d9c-f001-4844-8b60-8b2e64ba19ee"),
                            Description = "This is country number 2",
                            Name = "Country 2"
                        },
                        new
                        {
                            Id = new Guid("6d63fc05-f890-43de-98ea-3ca6104cf006"),
                            Description = "This is country number 3",
                            Name = "Country 3"
                        },
                        new
                        {
                            Id = new Guid("f9f21a1d-dffa-49ba-9f45-8655c6ed19f1"),
                            Description = "This is country number 4",
                            Name = "Country 4"
                        },
                        new
                        {
                            Id = new Guid("9401773d-f874-4de0-a88d-296afc7c77aa"),
                            Description = "This is country number 5",
                            Name = "Country 5"
                        },
                        new
                        {
                            Id = new Guid("dd0a2bda-6ad7-411c-b988-228006ce992d"),
                            Description = "This is country number 6",
                            Name = "Country 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
