// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiflheimsForge.Data;

#nullable disable

namespace NiflheimsForge.Data.Data.Migrations
{
    [DbContext(typeof(NiflheimsForgeDBContext))]
    [Migration("20240311090211_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NiflheimsForge.Core.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("451a6442-8251-4390-8cbf-e983dea9dbff"),
                            Description = "This is country number 1",
                            Name = "Country 1"
                        },
                        new
                        {
                            Id = new Guid("964dbef7-5792-481d-8c52-73f5426230a5"),
                            Description = "This is country number 2",
                            Name = "Country 2"
                        },
                        new
                        {
                            Id = new Guid("a2985416-d868-4c48-a5c3-5260d859295f"),
                            Description = "This is country number 3",
                            Name = "Country 3"
                        },
                        new
                        {
                            Id = new Guid("7da807f5-8dfa-4ed2-88ff-b5342496a60d"),
                            Description = "This is country number 4",
                            Name = "Country 4"
                        },
                        new
                        {
                            Id = new Guid("a8a94071-ea2d-4efc-98af-04458fd15e86"),
                            Description = "This is country number 5",
                            Name = "Country 5"
                        },
                        new
                        {
                            Id = new Guid("51ddd4bc-8ee1-41e2-a067-8f285cebb291"),
                            Description = "This is country number 6",
                            Name = "Country 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
