// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiflheimsForge.Data;

#nullable disable

namespace NiflheimsForge.Data.Data.Migrations
{
    [DbContext(typeof(NiflheimsForgeDBContext))]
    [Migration("20240313084329_FourthMigration")]
    partial class FourthMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NiflheimsForge.Core.Models.Country", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8a07c44-988d-4f43-919e-d35711bbb9e4"),
                            Description = "This is country number 1",
                            Name = "Country 1"
                        },
                        new
                        {
                            Id = new Guid("f7f3dd96-2482-4f52-9a8c-44f23059289d"),
                            Description = "This is country number 2",
                            Name = "Country 2"
                        },
                        new
                        {
                            Id = new Guid("d96131a0-c431-4e36-9e51-0e99f04f6116"),
                            Description = "This is country number 3",
                            Name = "Country 3"
                        },
                        new
                        {
                            Id = new Guid("36d91f89-38cb-490b-9452-1237f5ad3ba0"),
                            Description = "This is country number 4",
                            Name = "Country 4"
                        },
                        new
                        {
                            Id = new Guid("4fb9cc4e-cb7d-423b-aea3-da5624b0f1dc"),
                            Description = "This is country number 5",
                            Name = "Country 5"
                        },
                        new
                        {
                            Id = new Guid("a74fa8b8-513e-4846-a820-0f7a36134a50"),
                            Description = "This is country number 6",
                            Name = "Country 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
