// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiflheimsForge.Data;

#nullable disable

namespace NiflheimsForge.Data.Data.Migrations
{
    [DbContext(typeof(NiflheimsForgeDBContext))]
    [Migration("20240311095027_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NiflheimsForge.Core.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13d87701-dc16-4f80-9a41-1aed886b0ed3"),
                            Description = "This is country number 1",
                            Name = "Country 1"
                        },
                        new
                        {
                            Id = new Guid("9db714ca-de11-4052-9604-641423353586"),
                            Description = "This is country number 2",
                            Name = "Country 2"
                        },
                        new
                        {
                            Id = new Guid("39072d2b-1b3d-4d8e-bee4-2279f12e6667"),
                            Description = "This is country number 3",
                            Name = "Country 3"
                        },
                        new
                        {
                            Id = new Guid("9cc5363a-f913-4954-b5bd-b2a4b73dab64"),
                            Description = "This is country number 4",
                            Name = "Country 4"
                        },
                        new
                        {
                            Id = new Guid("3a1fb89e-54cd-4a7f-b426-3a5a74709eeb"),
                            Description = "This is country number 5",
                            Name = "Country 5"
                        },
                        new
                        {
                            Id = new Guid("77e1b3e4-5658-4c5b-94ed-9035f2bdd7a8"),
                            Description = "This is country number 6",
                            Name = "Country 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
