// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiflheimsForge.Data;

#nullable disable

namespace NiflheimsForge.Data.Data.Migrations
{
    [DbContext(typeof(NiflheimsForgeDBContext))]
    partial class NiflheimsForgeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NiflheimsForge.Core.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88adeff1-15c3-43da-8660-1871f44cb5f9"),
                            Description = "This is country number 1",
                            Name = "Country 1"
                        },
                        new
                        {
                            Id = new Guid("20d0cc3e-031d-48e6-8ccf-a97a53ab5574"),
                            Description = "This is country number 2",
                            Name = "Country 2"
                        },
                        new
                        {
                            Id = new Guid("ae78d369-5e9f-4b1c-ae64-be53b37bfc1c"),
                            Description = "This is country number 3",
                            Name = "Country 3"
                        },
                        new
                        {
                            Id = new Guid("256b71c2-2256-4eec-b2f4-9b709370e764"),
                            Description = "This is country number 4",
                            Name = "Country 4"
                        },
                        new
                        {
                            Id = new Guid("d92322e5-9210-48c3-8882-2ac26768ebac"),
                            Description = "This is country number 5",
                            Name = "Country 5"
                        },
                        new
                        {
                            Id = new Guid("2b3a8ec4-25dd-4ac5-859a-692a6b6caef7"),
                            Description = "This is country number 6",
                            Name = "Country 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
